name: Deploy Backend to Azure App Service

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/azure-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create deployment bundle (zip)
        run: |
          mkdir deploy
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='venv' \
            --exclude='__pycache__' \
            --exclude='*.pyc' \
            --exclude='tests' \
            ./ ./deploy/
          cd deploy
          zip -r ../app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-002-gen10-step3-1-py-oshima1'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: app.zip
        env:
          SCM_DO_BUILD_DURING_DEPLOYMENT: true
